### ISSUE TITLE
Glitch with --interface-family=ipv6

### ISSUE THREAD

**Issue by neingeist** [SpComb/go-nsupdate#5]
I've noticed a glitch using `--interface-family=ipv6`: It can happen that a IPv4 address is used for the update.

I have go-nsupdate running using `--watch`:
~~~
/usr/local/bin/go-nsupdate \
--tsig-algorithm=hmac-sha512 --tsig-name=bims.dyn.bl0rg.net \
--interface=eth0 --interface-family=ipv6 --watch bims.dyn.bl0rg.net
~~~

Among the IPv6 addresses there was once an IPv4 address used for the nsupdate:
~~~
...
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 AddrSet iface=eth0: up 2a02:8109:9e40:3f61:11:32ff:fe23:913f
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 addrs update...                                           
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update...                                                 
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update query...                                           
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update answer                                             
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 AddrSet iface=eth0: up 192.168.144.3                      
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 addrs update...                                           
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 update...                                                 
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 update query...                                           
Jun 20 11:20:22 bims go-nsupdate[342693]: 2022/06/20 11:20:22 update answer                                             
Jun 20 11:22:04 bims go-nsupdate[342693]: 2022/06/20 11:22:04 AddrSet iface=eth0: up 2a02:8109:9e40:3f61:11:32ff:fe23:913f
...
~~~

@SpComb Any idea how this could happen?

**Comment by neingeist** [comment]
(I am 100% sure go-nsupdate was running with `--interface-family=ipv6` at 11:20:21)

**Comment by SpComb** [comment]
Looks like the family is only used for the initial `InterfaceAddrs(...)` -> `netlink.AddrList(...)`, but not for the `netlink.AddrSubscribe(...)` -> `chan netlink.AddrUpdate` events. I guess it counts as a bug, if it's just not implemented everywhere it should be :)

**Comment by neingeist** [comment]
Yeah it counts as a bug :) From my vague understanding of the netlink Go API I'd say there is no way to filter for the family in `AddrSubscribe`, so #6 filters explicitly. At 11:20 I should have had my 12h "IPv4 update", but it was correctly filtered, so this is looking good. I'd just test for the full day and then I'll remove the Draft status from the PR again!
