### ISSUE TITLE
Activate GitHub Wiki?

### ISSUE THREAD

**Issue by neingeist** [SpComb/go-nsupdate#9]
I'm a bit confused because the "Wiki" tab is there but it redirects to the main project page. Could you have a look to activate it? I'd like to contribute a wiki page "How to use go-nsupdate in a systemd service" :)

**Comment by SpComb** [comment]
The GitHub Wiki was in "Restrict editing to collaborators only" mode by default. It should be editable now.

I'll lock it back down again if there's some spam problem, and figure out the collaborators thing :thinking:

**Comment by neingeist** [comment]
Awesome! → https://github.com/SpComb/go-nsupdate/wiki/How-to-run-go-nsupdate-using-systemd 🎉
